open Interpret

(******************************** code generated by Coq **********************)

let test () = ParP ((NuPl (fun x -> ZeroP)), ZeroP)

(********************************* entry point ***********************************)
